import assert from "node:assert/strict";
import { test } from "node:test";
import net from "node:net";
import dgram from "node:dgram";
import { once } from "node:events";
import { parseNameservers, startProxyFixture } from "../tests/support/proxy-fixture-server.mjs";

const dnsQuery = (id, name) => Buffer.concat([
  Buffer.from([0, id, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
  ...name.split(".").map(label => Buffer.concat([Buffer.from([label.length]), Buffer.from(label)])),
  Buffer.from([0, 0, 1, 0, 1]),
]);

test("infrastructure DNS uses the resolvers the container was given", () => {
  assert.deepEqual(parseNameservers("# Generated by Docker Engine.\nnameserver 127.0.0.11\nsearch local\noptions ndots:0\n\n# ExtServers: [host(192.168.1.1)]\n"), [{ address: "127.0.0.11", port: 53 }]);
  assert.deepEqual(parseNameservers("search dns.podman\nnameserver 10.89.0.1\nnameserver fd00::1\n"), [{ address: "10.89.0.1", port: 53 }, { address: "fd00::1", port: 53 }]);
  assert.deepEqual(parseNameservers("nameserver not-an-address\n#nameserver 10.0.0.1\n"), []);
});

test("forwards only infrastructure names to the container resolver", async () => {
  const upstream = dgram.createSocket("udp4");
  const forwarded = [];
  upstream.on("message", (query, remote) => {
    forwarded.push(query);
    const answer = Buffer.from(query);
    answer.writeUInt16BE(0x8180, 2);
    upstream.send(answer, remote.port, remote.address);
  });
  upstream.bind(0, "127.0.0.1");
  await once(upstream, "listening");
  const fixture = await startProxyFixture({
    ip: "127.0.0.1",
    ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 },
    nameservers: [{ address: "127.0.0.1", port: upstream.address().port }],
  });
  const socket = dgram.createSocket("udp4");
  const ask = async query => {
    const response = once(socket, "message");
    socket.send(query, fixture.ports.dnsUdp, "127.0.0.1");
    return (await response)[0];
  };
  try {
    // The local reply to a non-infrastructure name proves it was not forwarded.
    assert.equal((await ask(dnsQuery(1, "example.com"))).readUInt16BE(2), 0x8183);
    assert.equal(forwarded.length, 0);
    const answer = await ask(dnsQuery(2, "weaver-postgres"));
    assert.equal(answer.readUInt16BE(0), 2);
    assert.equal(answer.readUInt16BE(2), 0x8180);
    assert.equal(forwarded.length, 1);
  } finally { socket.close(); upstream.close(); await fixture.close(); }
});

test("a silent resolver does not keep an infrastructure name from the one that answers", async () => {
  const silent = dgram.createSocket("udp4");
  const asked = once(silent, "message");
  silent.bind(0, "127.0.0.1");
  await once(silent, "listening");
  const answering = dgram.createSocket("udp4");
  answering.on("message", (query, remote) => {
    const response = Buffer.from(query);
    response.writeUInt16BE(0x8180, 2);
    answering.send(response, remote.port, remote.address);
  });
  answering.bind(0, "127.0.0.1");
  await once(answering, "listening");
  const fixture = await startProxyFixture({
    ip: "127.0.0.1",
    ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 },
    nameservers: [{ address: "127.0.0.1", port: silent.address().port }, { address: "127.0.0.1", port: answering.address().port }],
  });
  const socket = dgram.createSocket("udp4");
  try {
    const response = once(socket, "message");
    socket.send(dnsQuery(7, "nntp"), fixture.ports.dnsUdp, "127.0.0.1");
    const [answer] = await response;
    assert.equal(answer.readUInt16BE(0), 7);
    assert.equal(answer.readUInt16BE(2), 0x8180);
    await asked;
  } finally {
    socket.close(); silent.close(); answering.close();
    await fixture.close();
  }
});

test("canary answers destination DNS locally and records host queries", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 } });
  const socket = dgram.createSocket("udp4");
  try {
    const header = Buffer.from([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]);
    const question = Buffer.concat([...["news", "proxy", "test"].map(label => Buffer.concat([Buffer.from([label.length]), Buffer.from(label)])), Buffer.from([0, 0, 1, 0, 1])]);
    const response = once(socket, "message");
    socket.send(Buffer.concat([header, question]), fixture.ports.dnsUdp, "127.0.0.1");
    const [body] = await response;
    assert.equal(body.readUInt16BE(6), 1);
    assert.deepEqual([...body.subarray(-4)], [127, 0, 0, 1]);
    assert.equal(fixture.events.filter(event => event.kind === "direct-dns").length, 1);
  } finally { socket.close(); await fixture.close(); }
});

test("HTTP CONNECT preserves pipelined data and refuses non-fixture targets", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 } });
  try {
    const request = async (host, port, payload = "", authorization = Buffer.from("fixture:fixture").toString("base64")) => {
      const socket = net.connect(fixture.ports.primary, "127.0.0.1");
      socket.setTimeout(3000, () => socket.destroy(new Error("fixture timeout")));
      const chunks = [];
      socket.on("data", chunk => chunks.push(chunk));
      socket.write(`CONNECT ${host}:${port} HTTP/1.1\r\nProxy-Authorization: Basic ${authorization}\r\n\r\n${payload}`);
      await once(socket, "close");
      return Buffer.concat(chunks).toString();
    };
    const good = await request("news.proxy.test", fixture.ports.http, "GET /feed.xml HTTP/1.1\r\nHost: news.proxy.test\r\nConnection: close\r\n\r\n");
    assert.match(good, /200 Connection Established/);
    assert.match(good, /<rss/);
    assert.match(await request("unrelated.invalid", 443), /502 Bad Gateway/);
    assert.match(await request("news.proxy.test", fixture.ports.http, "", Buffer.from("fixture:fixture").toString("base64").toUpperCase()), /407 Proxy Authentication Required/);
    assert.equal(fixture.events.filter(event => event.kind === "connected").length, 1);
  } finally { await fixture.close(); }
});

test("SOCKS5 accepts a pipelined authenticated handshake", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 } });
  try {
    const socket = net.connect(fixture.ports.secondary, "127.0.0.1");
    socket.setTimeout(3000, () => socket.destroy(new Error("fixture timeout")));
    const port = Buffer.alloc(2); port.writeUInt16BE(fixture.ports.http);
    const chunks = [];
    socket.on("data", chunk => chunks.push(chunk));
    socket.write(Buffer.concat([
      Buffer.from([5, 1, 2, 1, 7]), Buffer.from("fixture"), Buffer.from([7]), Buffer.from("fixture"),
      Buffer.from([5, 1, 0, 1, 127, 0, 0, 1]), port,
      Buffer.from("GET /feed.xml HTTP/1.1\r\nHost: news.proxy.test\r\nConnection: close\r\n\r\n"),
    ]));
    await once(socket, "close");
    const body = Buffer.concat(chunks);
    assert.deepEqual([...body.subarray(0, 4)], [5, 2, 1, 0]);
    assert.match(body.toString(), /<rss/);
    assert.equal(fixture.events.find(event => event.kind === "connected")?.route, "secondary");
  } finally { await fixture.close(); }
});
