import assert from "node:assert/strict";
import { test } from "node:test";
import net from "node:net";
import dgram from "node:dgram";
import { once } from "node:events";
import { parseAddressList, parseHostTable, parseNameservers, parseRouteList, startProxyFixture } from "../tests/support/proxy-fixture-server.mjs";

const dnsQuery = (id, name) => Buffer.concat([
  Buffer.from([0, id, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
  ...name.split(".").map(label => Buffer.concat([Buffer.from([label.length]), Buffer.from(label)])),
  Buffer.from([0, 0, 1, 0, 1]),
]);

test("infrastructure DNS uses the resolvers the container was given", () => {
  assert.deepEqual(parseNameservers("# Generated by Docker Engine.\nnameserver 127.0.0.11\nsearch local\noptions ndots:0\n\n# ExtServers: [host(192.168.1.1)]\n"), [{ address: "127.0.0.11", port: 53 }]);
  assert.deepEqual(parseNameservers("search dns.podman\nnameserver 10.89.0.1\nnameserver fd00::1\n"), [{ address: "10.89.0.1", port: 53 }, { address: "fd00::1", port: 53 }]);
  assert.deepEqual(parseNameservers("nameserver not-an-address\n#nameserver 10.0.0.1\n"), []);
});

test("forwards only infrastructure names to the container resolver", async () => {
  const upstream = dgram.createSocket("udp4");
  const forwarded = [];
  upstream.on("message", (query, remote) => {
    forwarded.push(query);
    const answer = Buffer.from(query);
    answer.writeUInt16BE(0x8180, 2);
    upstream.send(answer, remote.port, remote.address);
  });
  upstream.bind(0, "127.0.0.1");
  await once(upstream, "listening");
  const fixture = await startProxyFixture({
    ip: "127.0.0.1",
    ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 },
    nameservers: [{ address: "127.0.0.1", port: upstream.address().port }],
  });
  const socket = dgram.createSocket("udp4");
  const ask = async query => {
    const response = once(socket, "message");
    socket.send(query, fixture.ports.dnsUdp, "127.0.0.1");
    return (await response)[0];
  };
  try {
    // The local reply to a non-infrastructure name proves it was not forwarded.
    assert.equal((await ask(dnsQuery(1, "example.com"))).readUInt16BE(2), 0x8183);
    assert.equal(forwarded.length, 0);
    const answer = await ask(dnsQuery(2, "weaver-postgres"));
    assert.equal(answer.readUInt16BE(0), 2);
    assert.equal(answer.readUInt16BE(2), 0x8180);
    assert.equal(forwarded.length, 1);
  } finally { socket.close(); upstream.close(); await fixture.close(); }
});

test("a silent resolver does not keep an infrastructure name from the one that answers", async () => {
  const silent = dgram.createSocket("udp4");
  const asked = once(silent, "message");
  silent.bind(0, "127.0.0.1");
  await once(silent, "listening");
  const answering = dgram.createSocket("udp4");
  answering.on("message", (query, remote) => {
    const response = Buffer.from(query);
    response.writeUInt16BE(0x8180, 2);
    answering.send(response, remote.port, remote.address);
  });
  answering.bind(0, "127.0.0.1");
  await once(answering, "listening");
  const fixture = await startProxyFixture({
    ip: "127.0.0.1",
    ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 },
    nameservers: [{ address: "127.0.0.1", port: silent.address().port }, { address: "127.0.0.1", port: answering.address().port }],
  });
  const socket = dgram.createSocket("udp4");
  try {
    const response = once(socket, "message");
    socket.send(dnsQuery(7, "nntp"), fixture.ports.dnsUdp, "127.0.0.1");
    const [answer] = await response;
    assert.equal(answer.readUInt16BE(0), 7);
    assert.equal(answer.readUInt16BE(2), 0x8180);
    await asked;
  } finally {
    socket.close(); silent.close(); answering.close();
    await fixture.close();
  }
});

test("canary answers destination DNS locally and records host queries", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 } });
  const socket = dgram.createSocket("udp4");
  try {
    const header = Buffer.from([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]);
    const question = Buffer.concat([...["news", "proxy", "test"].map(label => Buffer.concat([Buffer.from([label.length]), Buffer.from(label)])), Buffer.from([0, 0, 1, 0, 1])]);
    const response = once(socket, "message");
    socket.send(Buffer.concat([header, question]), fixture.ports.dnsUdp, "127.0.0.1");
    const [body] = await response;
    assert.equal(body.readUInt16BE(6), 1);
    assert.deepEqual([...body.subarray(-4)], [127, 0, 0, 1]);
    assert.equal(fixture.events.filter(event => event.kind === "direct-dns").length, 1);
  } finally { socket.close(); await fixture.close(); }
});

test("HTTP CONNECT preserves pipelined data and refuses non-fixture targets", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 } });
  try {
    const request = async (host, port, payload = "", authorization = Buffer.from("fixture:fixture").toString("base64")) => {
      const socket = net.connect(fixture.ports.primary, "127.0.0.1");
      socket.setTimeout(3000, () => socket.destroy(new Error("fixture timeout")));
      const chunks = [];
      socket.on("data", chunk => chunks.push(chunk));
      socket.write(`CONNECT ${host}:${port} HTTP/1.1\r\nProxy-Authorization: Basic ${authorization}\r\n\r\n${payload}`);
      await once(socket, "close");
      return Buffer.concat(chunks).toString();
    };
    const good = await request("news.proxy.test", fixture.ports.http, "GET /feed.xml HTTP/1.1\r\nHost: news.proxy.test\r\nConnection: close\r\n\r\n");
    assert.match(good, /200 Connection Established/);
    assert.match(good, /<rss/);
    assert.match(await request("unrelated.invalid", 443), /502 Bad Gateway/);
    assert.match(await request("news.proxy.test", fixture.ports.http, "", Buffer.from("fixture:fixture").toString("base64").toUpperCase()), /407 Proxy Authentication Required/);
    assert.equal(fixture.events.filter(event => event.kind === "connected").length, 1);
  } finally { await fixture.close(); }
});

test("SOCKS5 accepts a pipelined authenticated handshake", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 } });
  try {
    const socket = net.connect(fixture.ports.secondary, "127.0.0.1");
    socket.setTimeout(3000, () => socket.destroy(new Error("fixture timeout")));
    const port = Buffer.alloc(2); port.writeUInt16BE(fixture.ports.http);
    const chunks = [];
    socket.on("data", chunk => chunks.push(chunk));
    socket.write(Buffer.concat([
      Buffer.from([5, 1, 2, 1, 7]), Buffer.from("fixture"), Buffer.from([7]), Buffer.from("fixture"),
      Buffer.from([5, 1, 0, 1, 127, 0, 0, 1]), port,
      Buffer.from("GET /feed.xml HTTP/1.1\r\nHost: news.proxy.test\r\nConnection: close\r\n\r\n"),
    ]));
    await once(socket, "close");
    const body = Buffer.concat(chunks);
    assert.deepEqual([...body.subarray(0, 4)], [5, 2, 1, 0]);
    assert.match(body.toString(), /<rss/);
    assert.equal(fixture.events.find(event => event.kind === "connected")?.route, "secondary");
  } finally { await fixture.close(); }
});

const zeroPorts = { primary: 0, secondary: 0, tertiary: 0, dns: 0, nntp: 0, http: 0, control: 0 };
const control = async (fixture, path, body) => {
  const response = await fetch(`http://127.0.0.1:${fixture.ports.control}${path}`, body ? { method: "POST", body: JSON.stringify(body) } : undefined);
  return { status: response.status, body: await response.json() };
};
const exchange = async (port, payload) => {
  const socket = net.connect(port, "127.0.0.1");
  socket.setTimeout(3000, () => socket.destroy(new Error("fixture timeout")));
  const chunks = [];
  socket.on("data", chunk => chunks.push(chunk));
  socket.write(payload);
  await once(socket, "close");
  return Buffer.concat(chunks);
};
const socksHandshake = port => {
  const portBytes = Buffer.alloc(2); portBytes.writeUInt16BE(port);
  return Buffer.concat([
    Buffer.from([5, 1, 2, 1, 7]), Buffer.from("fixture"), Buffer.from([7]), Buffer.from("fixture"),
    Buffer.from([5, 1, 0, 1, 127, 0, 0, 1]), portBytes,
    Buffer.from("GET /feed.xml HTTP/1.1\r\nHost: news.proxy.test\r\nConnection: close\r\n\r\n"),
  ]);
};

test("route, address and host lists parse strictly", () => {
  assert.deepEqual(parseRouteList(""), []);
  assert.deepEqual(parseRouteList("connect1, socks2,connect1"), ["connect1", "socks2"]);
  assert.equal(parseRouteList("all").length, 10);
  assert.throws(() => parseRouteList("connect9"), /unknown proxy fixture route/);
  assert.deepEqual(parseAddressList("", "10.0.0.1"), ["10.0.0.1"]);
  assert.deepEqual(parseAddressList("10.1.0.23,10.2.0.23", "10.0.0.1"), ["10.1.0.23", "10.2.0.23"]);
  assert.throws(() => parseAddressList("nntp", "10.0.0.1"), /invalid fixture address/);
  assert.deepEqual(parseHostTable('{"NNTP":["10.1.0.20","10.2.0.20"],"nntp2":"10.1.0.21"}'), { nntp: ["10.1.0.20", "10.2.0.20"], nntp2: ["10.1.0.21"] });
  assert.throws(() => parseHostTable('{"nntp":["bad"]}'), /invalid address/);
});

test("pool member routes answer forced CONNECT statuses and SOCKS replies, then recover", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", routes: ["connect3", "socks2"], ports: { ...zeroPorts, connect3: 0, socks2: 0 } });
  try {
    const connect = () => exchange(fixture.ports.connect3, `CONNECT news.proxy.test:${fixture.ports.http} HTTP/1.1\r\nProxy-Authorization: Basic ${Buffer.from("fixture:fixture").toString("base64")}\r\n\r\nGET /feed.xml HTTP/1.1\r\nHost: news.proxy.test\r\nConnection: close\r\n\r\n`);
    assert.equal((await control(fixture, "/", { route: "connect3", connectStatus: 503 })).status, 200);
    assert.match((await connect()).toString(), /^HTTP\/1\.1 503 Service Unavailable/);
    assert.equal((await control(fixture, "/", { route: "connect3", connectStatus: null })).status, 200);
    assert.match((await connect()).toString(), /<rss/);

    await control(fixture, "/", { route: "socks2", socksReply: 2 });
    const refused = await exchange(fixture.ports.socks2, socksHandshake(fixture.ports.http));
    assert.deepEqual([...refused.subarray(0, 6)], [5, 2, 1, 0, 5, 2]);
    await control(fixture, "/", { route: "socks2", socksReply: null });
    assert.match((await exchange(fixture.ports.socks2, socksHandshake(fixture.ports.http))).toString(), /<rss/);

    const connected = fixture.events.filter(event => event.kind === "connected");
    assert.deepEqual(connected.map(event => event.route), ["connect3", "socks2"]);
    assert.ok(connected.every(event => event.client === "127.0.0.1"));
    assert.equal((await control(fixture, "/", { route: "connect3", connectStatus: 42 })).status, 400);
    assert.equal((await control(fixture, "/", { route: "socks2", socksReply: 0 })).status, 400);
  } finally { await fixture.close(); }
});

test("event reads after a watermark return only newer events", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: zeroPorts });
  try {
    await exchange(fixture.ports.primary, `CONNECT unrelated.invalid:443 HTTP/1.1\r\nProxy-Authorization: Basic ${Buffer.from("fixture:fixture").toString("base64")}\r\n\r\n`);
    const first = await control(fixture, "/events?after=0");
    assert.equal(first.body.events.length, 1);
    const watermark = first.body.sequence;
    assert.deepEqual((await control(fixture, `/events?after=${watermark}`)).body.events, []);
    await exchange(fixture.ports.primary, `CONNECT unrelated.invalid:443 HTTP/1.1\r\nProxy-Authorization: Basic ${Buffer.from("fixture:fixture").toString("base64")}\r\n\r\n`);
    const next = await control(fixture, `/events?after=${watermark}`);
    assert.equal(next.body.events.length, 1);
    assert.ok(next.body.events[0].sequence > watermark);
    assert.equal((await control(fixture, "/events?after=-1")).status, 400);
  } finally { await fixture.close(); }
});

test("multi-network DNS answers every fixture address and the host table", async () => {
  const fixture = await startProxyFixture({
    ip: "127.0.0.1", ports: zeroPorts,
    addresses: ["10.1.0.23", "10.2.0.23"],
    hosts: { nntp: ["10.1.0.20", "10.2.0.20"] },
    nameservers: [],
  });
  const socket = dgram.createSocket("udp4");
  const ask = async query => {
    const response = once(socket, "message");
    socket.send(query, fixture.ports.dnsUdp, "127.0.0.1");
    return (await response)[0];
  };
  try {
    const fixtureName = await ask(dnsQuery(3, "news.proxy.test"));
    assert.equal(fixtureName.readUInt16BE(6), 2);
    assert.deepEqual([...fixtureName.subarray(-4)], [10, 2, 0, 23]);
    const infra = await ask(dnsQuery(4, "nntp"));
    assert.equal(infra.readUInt16BE(2), 0x8180);
    assert.equal(infra.readUInt16BE(6), 2);
    assert.deepEqual([...infra.subarray(-20, -16)], [10, 1, 0, 20]);
    assert.deepEqual([...infra.subarray(-4)], [10, 2, 0, 20]);
  } finally { socket.close(); await fixture.close(); }
});

test("download paths ignore the query string and the non-NZB body is served", async () => {
  const fixture = await startProxyFixture({ ip: "127.0.0.1", ports: zeroPorts });
  try {
    await control(fixture, "/", { nzb: "<nzb/>" });
    const probe = await fetch(`http://127.0.0.1:${fixture.ports.http}/probe.nzb?apikey=fixture-secret`);
    assert.equal(probe.status, 200);
    assert.equal(await probe.text(), "<nzb/>");
    const junk = await fetch(`http://127.0.0.1:${fixture.ports.http}/not-an-nzb.nzb`);
    assert.match(await junk.text(), /not an nzb/);
  } finally { await fixture.close(); }
});
