package fixturegen

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/scryer-media/weaver/e2e/internal/corpus"
)

// EnsureConfig says which fixtures must be present and how far to go to make
// them so.
type EnsureConfig struct {
	// Root is the harness root: the directory holding go.mod.
	Root string
	// Profiles are corpus profile names (see test-corpus/profiles.json).
	Profiles []string
	// Paths are ledger paths (testdata/<slug>/<file>). Profiles and Paths
	// are unioned; at least one of them must select something.
	Paths []string
	// NoFetch skips the published corpus and goes straight to generation.
	NoFetch bool
	// NoGenerate stops after the fetch: anything still missing is an error.
	NoGenerate bool
	// Digest checks every present file's BLAKE3 against the ledger instead
	// of only its size. It is what a pre-flight wants; a per-fixture check on
	// the seeding path can settle for the size.
	Digest bool
	// Workers bounds concurrent scenario generation. Zero means the
	// generator's default.
	Workers int
	// Concurrency bounds in-flight downloads. Zero means the fetcher's default.
	Concurrency int
	// Verbose echoes oracle output during generation.
	Verbose bool
	// Log receives progress lines. Nil discards them.
	Log io.Writer
}

// EnsureReport is what Ensure did, path by path.
type EnsureReport struct {
	// Wanted is every ledger path the config selected.
	Wanted []string
	// Present were already there and correct before anything was done.
	Present []string
	// Fetched came down from the published corpus.
	Fetched []string
	// Generated were rebuilt locally; GeneratedSlugs names their scenarios.
	Generated      []string
	GeneratedSlugs []string
	// FetchSkipped is why the published corpus was not consulted, or what
	// went wrong when it was; empty when the fetch ran clean.
	FetchSkipped string
	// LedgerChanged reports that generation rewrote test-corpus/sources.json:
	// the tree now describes a local corpus revision, not the published one.
	// Byte-reproducible families regenerate to identical digests and leave
	// the ledger as it was.
	LedgerChanged bool
	// Salted counts the wanted paths verified by presence alone, because their
	// writer draws a salt and their bytes cannot be pinned.
	Salted []string
}

// Ensure makes every selected fixture present, in this order: whatever is
// already on disk and matches the ledger is reused; whatever is missing is
// fetched from the published corpus when lock.json pins one; whatever is
// still missing after that is generated on the pinned toolchains. Fetched
// bytes are verified against the published manifest before they are written.
// Generated bytes are a local corpus revision — the ledger's sizes, digests
// and provenance for those scenarios are refreshed, and the tree is honest
// about which paths came from where.
//
// The published corpus is consulted first on purpose: it is what every other
// checkout runs against, and a fetch is minutes where a cold generation is an
// hour and needs Docker with the pinned oracle images.
func Ensure(ctx context.Context, config EnsureConfig) (EnsureReport, error) {
	report := EnsureReport{}
	if config.Log == nil {
		config.Log = io.Discard
	}
	logf := func(format string, args ...any) { fmt.Fprintf(config.Log, format+"\n", args...) }

	ledger, _, err := corpus.LoadLedger(config.Root)
	if err != nil {
		return report, err
	}
	if err := ValidateSaltedEntries(ledger, Recipes()); err != nil {
		return report, err
	}
	profiles, err := corpus.LoadProfiles(config.Root)
	if err != nil {
		return report, err
	}
	lock, err := corpus.LoadLock(config.Root)
	if err != nil {
		return report, err
	}
	wanted, err := selectWanted(ledger, profiles, config)
	if err != nil {
		return report, err
	}
	report.Wanted = wanted

	missing, err := missingPaths(config.Root, ledger, wanted, config.Digest)
	if err != nil {
		return report, err
	}
	report.Present = difference(wanted, missing)
	if len(missing) == 0 {
		return report, nil
	}

	// One ensure at a time per checkout: two harness processes that both find
	// the same fixture missing must not both regenerate it into the same
	// directory. The second waits, then re-checks and finds it present.
	release, err := lockEnsure(config.Root)
	if err != nil {
		return report, err
	}
	defer release()
	missing, err = missingPaths(config.Root, ledger, wanted, config.Digest)
	if err != nil {
		return report, err
	}
	report.Present = difference(wanted, missing)
	if len(missing) == 0 {
		return report, nil
	}
	logf("%d of %d fixture path(s) missing or stale", len(missing), len(wanted))

	// 1. The published corpus.
	beforeFetch := missing
	switch {
	case config.NoFetch:
		report.FetchSkipped = "fetch disabled"
	case !lock.Pinned():
		report.FetchSkipped = "nothing published yet: " + corpus.LockFile + " pins no manifest"
	default:
		logf("fetching from the published corpus (%s)", lock.Manifest.URL)
		err := corpus.Fetch(ctx, config.Root, lock, nil, corpus.FetchOptions{
			Concurrency: config.Concurrency,
			Only:        missing,
			Progress:    func(line string) { logf("  %s", line) },
		})
		if err != nil {
			if ctx.Err() != nil {
				return report, err
			}
			report.FetchSkipped = "fetch failed: " + err.Error()
		}
		missing, err = missingPaths(config.Root, ledger, wanted, true)
		if err != nil {
			return report, err
		}
		report.Fetched = difference(beforeFetch, missing)
	}
	for _, p := range wanted {
		if entry, ok := ledger.Entry(p); ok && entry.Salted {
			report.Salted = append(report.Salted, p)
		}
	}
	sort.Strings(report.Salted)
	if len(report.Salted) > 0 {
		logf("%d salted path(s) are verified by presence only; their writer draws a salt and their bytes cannot be pinned",
			len(report.Salted))
	}
	if report.FetchSkipped != "" {
		logf("published corpus not used: %s", report.FetchSkipped)
	}
	if len(missing) == 0 {
		return report, nil
	}

	// 2. The generator.
	if config.NoGenerate {
		return report, fmt.Errorf("%d fixture path(s) are missing and generation is disabled:\n  %s",
			len(missing), strings.Join(missing, "\n  "))
	}
	slugs := slugsOf(missing)
	logf("generating %d scenario(s) locally on the pinned toolchains: %s", len(slugs), strings.Join(slugs, ", "))
	ledgerBefore, err := os.ReadFile(corpus.HostPath(config.Root, corpus.LedgerFile))
	if err != nil {
		return report, err
	}
	results, err := Run(ctx, Config{
		Root:    config.Root,
		Slugs:   slugs,
		Workers: config.Workers,
		// Seeding regenerates fixtures to *match* the committed ledger, never
		// to redefine it. Refreshing digests here would turn a reproducibility
		// defect into a silent corpus fork: the bytes on disk would stop being
		// the bytes the ledger describes, and every consumer keyed on the
		// ledger — the NNTP seed fingerprint above all — would quietly move
		// with them. Writing the ledger is `cmd/fixturegen`'s job, on an
		// explicit generation run.
		UpdateLedger: false,
		Verbose:      config.Verbose,
		Log:          config.Log,
	})
	if err != nil {
		return report, err
	}
	for _, result := range results {
		if result.Slug != "" {
			report.GeneratedSlugs = append(report.GeneratedSlugs, result.Slug)
		}
	}
	sort.Strings(report.GeneratedSlugs)

	// The ledger must not have moved: generation ran with UpdateLedger off, so
	// anything here is a bug worth shouting about rather than absorbing.
	ledgerAfter, err := os.ReadFile(corpus.HostPath(config.Root, corpus.LedgerFile))
	if err != nil {
		return report, err
	}
	report.LedgerChanged = string(ledgerBefore) != string(ledgerAfter)
	if report.LedgerChanged {
		return report, fmt.Errorf("%s was rewritten during seeding; seeding must never redefine the corpus", corpus.LedgerFile)
	}

	still, err := missingPaths(config.Root, ledger, wanted, true)
	if err != nil {
		return report, err
	}
	report.Generated = difference(missing, still)
	if len(still) > 0 {
		// Tell the two cases apart. A path that is simply absent is a
		// generation failure; a path that exists but hashes differently is a
		// *reproducibility* failure, and saying so is the difference between
		// one named defect and a hundred downstream health errors.
		var absent, mismatched []string
		for _, p := range still {
			if _, err := os.Stat(corpus.HostPath(config.Root, p)); err == nil {
				mismatched = append(mismatched, p)
			} else {
				absent = append(absent, p)
			}
		}
		if len(mismatched) > 0 {
			return report, fmt.Errorf(
				"%d fixture(s) regenerated to different bytes than %s records — generation is not reproducible on this machine, "+
					"so the corpus cannot be rebuilt from recipes here; fetch the published corpus instead:\n  %s",
				len(mismatched), corpus.LedgerFile, strings.Join(mismatched, "\n  "))
		}
		return report, fmt.Errorf("%d fixture path(s) are still missing after generation:\n  %s",
			len(absent), strings.Join(absent, "\n  "))
	}
	return report, nil
}

// selectWanted resolves the config's profiles and explicit paths against the
// ledger. An explicit path the ledger does not list is an error: a fixture
// nobody described is exactly what the ledger exists to prevent.
func selectWanted(ledger *corpus.Ledger, profiles *corpus.Profiles, config EnsureConfig) ([]string, error) {
	all := ledger.Paths()
	set := make(map[string]struct{})
	for _, name := range config.Profiles {
		resolved, err := profiles.Resolve(name, all)
		if err != nil {
			return nil, err
		}
		for _, p := range resolved {
			set[p] = struct{}{}
		}
	}
	for _, p := range config.Paths {
		if _, ok := ledger.Entry(p); !ok {
			return nil, fmt.Errorf("%s is not a ledger path (see %s)", p, corpus.LedgerFile)
		}
		set[p] = struct{}{}
	}
	if len(set) == 0 {
		return nil, errors.New("ensure needs at least one profile or path")
	}
	wanted := make([]string, 0, len(set))
	for p := range set {
		wanted = append(wanted, p)
	}
	sort.Strings(wanted)
	return wanted, nil
}

// missingPaths returns the wanted paths that are absent, the wrong size, or —
// with digest set — the wrong bytes.
func missingPaths(root string, ledger *corpus.Ledger, wanted []string, digest bool) ([]string, error) {
	var missing []string
	for _, p := range wanted {
		entry, ok := ledger.Entry(p)
		if !ok {
			missing = append(missing, p)
			continue
		}
		host := corpus.HostPath(root, p)
		info, err := os.Stat(host)
		if err != nil || !info.Mode().IsRegular() {
			missing = append(missing, p)
			continue
		}
		if entry.Salted {
			// Present is the whole test. A salted fixture's bytes differ on
			// every machine that generates them, so there is nothing to compare
			// a size or a digest against — and comparing anyway is exactly how
			// a locally-generated one would be declared "missing" forever.
			continue
		}
		if info.Size() != entry.Size {
			missing = append(missing, p)
			continue
		}
		if !digest {
			continue
		}
		actual, err := corpus.DigestFile(host)
		if err != nil {
			return nil, err
		}
		if actual.BLAKE3 != entry.BLAKE3 {
			missing = append(missing, p)
		}
	}
	return missing, nil
}

// slugsOf maps ledger paths to the scenario directories that own them:
// testdata/<slug>/... is <slug>, and the shared clips are the "shared" recipe.
func slugsOf(paths []string) []string {
	set := make(map[string]struct{})
	for _, p := range paths {
		rest := strings.TrimPrefix(path.Clean(filepath.ToSlash(p)), "testdata/")
		if slug, _, ok := strings.Cut(rest, "/"); ok && slug != "" {
			set[slug] = struct{}{}
		}
	}
	slugs := make([]string, 0, len(set))
	for slug := range set {
		slugs = append(slugs, slug)
	}
	sort.Strings(slugs)
	return slugs
}

// ScenarioPaths returns the ledger paths a scenario directory owns.
func ScenarioPaths(ledger *corpus.Ledger, slug string) []string {
	prefix := "testdata/" + slug + "/"
	var paths []string
	for _, p := range ledger.Paths() {
		if strings.HasPrefix(p, prefix) {
			paths = append(paths, p)
		}
	}
	return paths
}
