package fixturegen

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestFamilyKeyIsJobSafe(t *testing.T) {
	cases := map[string]string{
		"RAR recovery volumes": "rar-recovery-volumes",
		"shared clips":         "shared-clips",
		"7z":                   "7z",
		"PAR2":                 "par2",
		"stream codec":         "stream-codec",
	}
	for family, want := range cases {
		if got := FamilyKey(family); got != want {
			t.Errorf("FamilyKey(%q) = %q, want %q", family, got, want)
		}
	}
}

// The publish workflow's whole contract with the recipe table: every recipe is
// in exactly one unit, the shared clips are the only stage-0 unit, every
// ledger path belongs to some unit, and the keys are unique — a duplicate key
// would make two matrix jobs upload the same artifact name.
func TestUnitsPartitionTheRecipesAndTheLedger(t *testing.T) {
	root := harnessRootForTest(t)
	listing, err := Units(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(listing.Units) == 0 || listing.Units[0].Name != SharedFamily || listing.Units[0].Stage != 0 {
		t.Fatalf("the first unit must be the stage-0 shared clips, got %+v", listing.Units[0])
	}
	seenKeys := map[string]bool{}
	seenSlugs := map[string]bool{}
	for _, unit := range listing.Units {
		if unit.Stage == 0 && unit.Name != SharedFamily {
			t.Errorf("unit %q is stage 0; only %q may be", unit.Name, SharedFamily)
		}
		if seenKeys[unit.Key] {
			t.Errorf("duplicate unit key %q", unit.Key)
		}
		seenKeys[unit.Key] = true
		if len(unit.Toolchains) == 0 {
			t.Errorf("unit %q credits no toolchain; the ledger records one for every generated byte", unit.Name)
		}
		for _, slug := range unit.Slugs {
			if seenSlugs[slug] {
				t.Errorf("slug %q appears in more than one unit", slug)
			}
			seenSlugs[slug] = true
		}
	}
	for _, recipe := range Recipes() {
		if !seenSlugs[recipe.Slug] {
			t.Errorf("recipe %q is in no unit", recipe.Slug)
		}
	}
	if len(listing.ArtifactToolchains) == 0 {
		t.Fatal("the artifact cache credits no toolchain")
	}
}

func TestLedgerPathsForSlugsPartitionsAndVerifies(t *testing.T) {
	root := harnessRootForTest(t)
	paths, err := LedgerPathsForSlugs(root, []string{"zip-unencrypted"}, true)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"testdata/zip-unencrypted/archive.zip",
		"testdata/zip-unencrypted/scenario.json",
	}
	if !reflect.DeepEqual(paths, want) {
		t.Fatalf("paths = %v, want %v", paths, want)
	}
	if _, err := LedgerPathsForSlugs(root, []string{"no-such-slug"}, false); err == nil {
		t.Fatal("an unknown slug must be an error")
	}
	// A scenario-only slug owns no bytes and is not an error: the workflow can
	// select a family that contains one.
	if paths, err := LedgerPathsForSlugs(root, []string{"stat-health-probe"}, false); err != nil || len(paths) != 0 {
		t.Fatalf("scenario-only slug: paths=%v err=%v", paths, err)
	}
}

func TestVerifyProducedReportsMissingEmptyAndUnledgered(t *testing.T) {
	root := t.TempDir()
	writeUnitsLedger(t, root, map[string]int{
		"testdata/alpha/present.bin": 3,
		"testdata/alpha/missing.bin": 3,
		"testdata/alpha/empty.bin":   3,
	})
	mustWrite(t, filepath.Join(root, "testdata/alpha/present.bin"), "abc")
	mustWrite(t, filepath.Join(root, "testdata/alpha/empty.bin"), "")
	mustWrite(t, filepath.Join(root, "testdata/alpha/stray.bin"), "unledgered")
	mustWrite(t, filepath.Join(root, "testdata/alpha/scenario.json"), "{}")

	err := VerifyProduced(root, []string{
		"testdata/alpha/present.bin",
		"testdata/alpha/missing.bin",
		"testdata/alpha/empty.bin",
		"testdata/alpha/scenario.json",
	})
	if err == nil {
		t.Fatal("expected problems")
	}
	for _, expected := range []string{
		"missing.bin: no recipe produced it",
		"empty.bin: was produced empty",
		"stray.bin: produced but not listed",
	} {
		if !strings.Contains(err.Error(), expected) {
			t.Errorf("missing problem %q in:\n%v", expected, err)
		}
	}
	if strings.Contains(err.Error(), "present.bin") || strings.Contains(err.Error(), "scenario.json") {
		t.Errorf("present.bin and scenario.json are fine and must not be reported:\n%v", err)
	}
}

// harnessRootForTest walks up to the real harness root (the tests run from
// internal/fixturegen).
func harnessRootForTest(t *testing.T) string {
	t.Helper()
	directory, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(directory, "go.mod")); err == nil {
			return directory
		}
		parent := filepath.Dir(directory)
		if parent == directory {
			t.Fatal("no go.mod above the test directory")
		}
		directory = parent
	}
}

func writeUnitsLedger(t *testing.T, root string, files map[string]int) {
	t.Helper()
	const zero = "0000000000000000000000000000000000000000000000000000000000000000"
	entries := ""
	for path, size := range files {
		if entries != "" {
			entries += ",\n"
		}
		entries += `    {"path":"` + path + `","size":` + itoa(size) + `,"blake3":"` + zero + `","format":"bin","source":{"kind":"generated","generator":"fixturegen","toolchains":["rarlab-7.23"]}}`
	}
	mustWrite(t, filepath.Join(root, "test-corpus/toolchains.json"), `{
  "schema_version": 1,
  "docker_base": "debian:bookworm-slim@sha256:`+zero+`",
  "rar_writers": [{"id": "rarlab-7.23", "image": "weaver-e2e-rarlab:7.23"}],
  "par2_generator": {"id": "par2cmdline-turbo-1.4.0"}
}`)
	mustWrite(t, filepath.Join(root, "test-corpus/sources.json"), `{
  "schema_version": 1,
  "toolchains": "test-corpus/toolchains.json",
  "generators": {"fixturegen": {"path": "cmd/fixturegen", "toolchains": ["rarlab-7.23"]}},
  "files": [
`+entries+`
  ]
}`)
}

func mustWrite(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}

func itoa(value int) string {
	if value == 0 {
		return "0"
	}
	digits := ""
	for value > 0 {
		digits = string(rune('0'+value%10)) + digits
		value /= 10
	}
	return digits
}
