package rawstack

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// A certificate naming only localhost fails NZBGet's name check on a 127.0.0.1
// dial, because OpenSSL's check never consults the iPAddress SANs. The dialled
// literal therefore has to appear as a DNS name as well.
func TestCertificateNamesCarryAnIPHostInBothFields(t *testing.T) {
	dnsNames, ipAddresses := CertificateNames("127.0.0.1")
	if !containsString(dnsNames, "127.0.0.1") {
		t.Fatalf("a dialled IP literal must be a DNS name too, got %v", dnsNames)
	}
	if !containsString(ipAddresses, "127.0.0.1") {
		t.Fatalf("a dialled IP literal must stay an IP SAN, got %v", ipAddresses)
	}
	if !containsString(dnsNames, "localhost") {
		t.Fatalf("localhost must remain a DNS name, got %v", dnsNames)
	}
}

func TestCertificateNamesDoNotRepeatTheDefaults(t *testing.T) {
	dnsNames, ipAddresses := CertificateNames("localhost")
	if len(dnsNames) != 1 || dnsNames[0] != "localhost" {
		t.Fatalf("localhost must not be named twice, got %v", dnsNames)
	}
	if len(ipAddresses) != 2 {
		t.Fatalf("a named host adds no IP SAN, got %v", ipAddresses)
	}
}

func TestServerEnvironmentCarriesTheDerivedNames(t *testing.T) {
	stack, err := New(usableConfig(t))
	if err != nil {
		t.Fatal(err)
	}
	var names string
	for _, entry := range stack.serverEnvironment() {
		if strings.HasPrefix(entry, "NNTP_TLS_DNS_NAMES=") {
			names = strings.TrimPrefix(entry, "NNTP_TLS_DNS_NAMES=")
		}
	}
	if !strings.Contains(names, "127.0.0.1") {
		t.Fatalf("the server is asked for a certificate that does not name the dialled host: %q", names)
	}
}

// The server reuses whatever material is already in the directory, so a
// certificate generated for other names is never regenerated on its own.
func TestCertificateCheckRejectsAStaleCertificate(t *testing.T) {
	config := settle(usableConfig(t))
	writeTestCertificate(t, config.CertDir, []string{"localhost"}, []net.IP{net.ParseIP("127.0.0.1")})
	check := certificateCheck(config)
	if check.Status == CheckOK {
		t.Fatalf("a certificate that does not name the dialled host must be refused")
	}
	if !strings.Contains(check.Reason, config.CertDir) {
		t.Fatalf("the reason must name the directory to delete, got %q", check.Reason)
	}
}

func TestCertificateCheckAcceptsAMatchingCertificate(t *testing.T) {
	config := settle(usableConfig(t))
	dnsNames, ipAddresses := CertificateNames(config.Host)
	var parsed []net.IP
	for _, address := range ipAddresses {
		parsed = append(parsed, net.ParseIP(address))
	}
	writeTestCertificate(t, config.CertDir, dnsNames, parsed)
	if check := certificateCheck(config); check.Status != CheckOK {
		t.Fatalf("a matching certificate was refused: %s", check.Reason)
	}
}

func TestCertificateCheckPassesWhenNothingIsGeneratedYet(t *testing.T) {
	config := settle(usableConfig(t))
	if check := certificateCheck(config); check.Status != CheckOK {
		t.Fatalf("an absent certificate is generated by the server, not a failure: %s", check.Reason)
	}
}

func writeTestCertificate(t *testing.T, directory string, dnsNames []string, ipAddresses []net.IP) {
	t.Helper()
	if err := os.MkdirAll(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	template := &x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject:      pkix.Name{CommonName: "test"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(time.Hour),
		DNSNames:     dnsNames,
		IPAddresses:  ipAddresses,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	encoded := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	if err := os.WriteFile(filepath.Join(directory, "server.pem"), encoded, 0o644); err != nil {
		t.Fatal(err)
	}
}
