package weaver

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCollectFixtureStagingFilesIncludesLocalSharedAndFixtureAssets(t *testing.T) {
	localDir := t.TempDir()
	sharedRoot := t.TempDir()
	fixtureRoot := t.TempDir()

	writeStageTestFile(t, filepath.Join(localDir, "local.bin"), []byte("local"))
	writeStageTestFile(t, filepath.Join(sharedRoot, "shared.bin"), []byte("shared"))
	writeStageTestFile(t, filepath.Join(fixtureRoot, "source-slug", "archive.bin"), []byte("fixture"))

	staged, err := collectFixtureStagingFiles(
		localDir,
		true,
		sharedRoot,
		[]string{"shared.bin::renamed-shared.bin"},
		fixtureRoot,
		[]string{"source-slug/archive.bin::Season 01/obfuscated.bin"},
	)
	if err != nil {
		t.Fatalf("collect staged files: %v", err)
	}
	if len(staged) != 3 {
		t.Fatalf("expected 3 staged files, got %d", len(staged))
	}

	got := map[string]string{}
	for _, file := range staged {
		data, err := os.ReadFile(file.source)
		if err != nil {
			t.Fatalf("read staged source %s: %v", file.source, err)
		}
		got[file.name] = string(data)
	}

	if got["local.bin"] != "local" {
		t.Fatalf("expected local.bin payload, got %#v", got)
	}
	if got["renamed-shared.bin"] != "shared" {
		t.Fatalf("expected renamed shared asset payload, got %#v", got)
	}
	if got[filepath.Join("Season 01", "obfuscated.bin")] != "fixture" {
		t.Fatalf("expected fixture asset payload, got %#v", got)
	}
}

func TestCollectFixtureStagingFilesRejectsDuplicateStagedNames(t *testing.T) {
	localDir := t.TempDir()
	sharedRoot := t.TempDir()
	fixtureRoot := t.TempDir()

	writeStageTestFile(t, filepath.Join(sharedRoot, "shared.bin"), []byte("shared"))
	writeStageTestFile(t, filepath.Join(fixtureRoot, "source-slug", "archive.bin"), []byte("fixture"))

	_, err := collectFixtureStagingFiles(
		localDir,
		false,
		sharedRoot,
		[]string{"shared.bin::duplicate.bin"},
		fixtureRoot,
		[]string{"source-slug/archive.bin::duplicate.bin"},
	)
	if err == nil {
		t.Fatal("expected duplicate staged filename error")
	}
	if !strings.Contains(err.Error(), "duplicate staged filename") {
		t.Fatalf("expected duplicate filename error, got %v", err)
	}
}

func TestRar5SolidEncryptedMissingMiddlePar2FixtureRequiresRepair(t *testing.T) {
	const slug = "rar5-solid-encrypted-missing-middle-par2"
	fixtureDir := filepath.Join(testdataDir(), slug)

	scenario, err := loadScenario(fixtureDir)
	if err != nil {
		t.Fatalf("load scenario: %v", err)
	}
	if scenario.ExpectedOutcome != "repair_then_success" {
		t.Fatalf("expected repair_then_success, got %q", scenario.ExpectedOutcome)
	}
	if scenario.Password != "weaver-e2e-repair-password" {
		t.Fatalf("expected encrypted RAR password, got %q", scenario.Password)
	}
	if len(scenario.RequiredJobEvents) != 1 || scenario.RequiredJobEvents[0] != "RepairComplete" {
		t.Fatalf("expected RepairComplete requirement, got %#v", scenario.RequiredJobEvents)
	}
	// Verification remains bounded at four. Three passes are typical, but a
	// fourth conservative scan is valid when an incomplete promoted volume
	// briefly has no concrete queued or active pipeline work. What this
	// assertion guards is that verification stays bounded; an unbounded re-scan
	// is the regression.
	if scenario.MaxJobEventCounts["JobVerificationStarted"] != 4 {
		t.Fatalf("expected bounded pre-repair verification, got %#v", scenario.MaxJobEventCounts)
	}
	// The payload is regenerated by the fixture generator on every corpus
	// revision, so its digest is not a constant: assert the oracle is present
	// and well-formed rather than pin a value that legitimately moves.
	digest, ok := scenario.ExpectedOutputBLAKE3["work/payload/movie.mkv"]
	if !ok || len(digest) != 64 || strings.Trim(digest, "0123456789abcdef") != "" {
		t.Fatalf("expected a lowercase 64-hex movie output BLAKE3 oracle, got %#v", scenario.ExpectedOutputBLAKE3)
	}

	foundCanonical := false
	for _, candidate := range canonicalFixtureSlugs {
		if candidate == slug {
			foundCanonical = true
			break
		}
	}
	if !foundCanonical {
		t.Fatalf("%s must run in the canonical E2E suite", slug)
	}

	for _, name := range []string{
		"archive.part1.rar",
		"archive.part2.rar",
		"archive.part4.rar",
		"archive.par2",
	} {
		info, err := os.Stat(filepath.Join(fixtureDir, name))
		if err != nil {
			t.Fatalf("expected fixture asset %s: %v", name, err)
		}
		if info.Size() == 0 {
			t.Fatalf("fixture asset %s is empty", name)
		}
	}
	if _, err := os.Stat(filepath.Join(fixtureDir, "archive.part3.rar")); !os.IsNotExist(err) {
		t.Fatalf("interior RAR volume must be absent from the fixture, stat err=%v", err)
	}
	par2Volumes, err := filepath.Glob(filepath.Join(fixtureDir, "archive.vol*.par2"))
	if err != nil {
		t.Fatalf("glob recovery volumes: %v", err)
	}
	if len(par2Volumes) == 0 {
		t.Fatal("fixture must provide PAR2 recovery volumes")
	}
}

func writeStageTestFile(t *testing.T, path string, data []byte) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
